### ISSUE TITLE
Където може да се ползват големи линкове

### ISSUE THREAD

**Issue by antitoxic** [obshtestvo/signali-theme#6]
Тези 2 линка, един до друг водят до едно и също и могат да се обединят в 1 `<a>` елемент:
- https://github.com/obshtestvo/signali-theme/blob/master/research/index.html#L206
- https://github.com/obshtestvo/signali-theme/blob/master/research/index.html#L207

**Comment by botodorov** [comment]
fixed

**Comment by botodorov** [comment]
fixed

**Comment by antitoxic** [comment]
@botodorov Натискай "Close" просто следк ато ги оправиш :)
