### ISSUE TITLE
Неточно наименован елемент `forbidden-password`

### ISSUE THREAD

**Issue by antitoxic** [obshtestvo/signali-theme#7]
`forbidden` значи забранен, не забравен :smiley: 

Забравен е `forgotten`. 

И гледайки този елемент няма нужда да е custom element. Това е просто линк нали?

**Comment by botodorov** [comment]
има 2-3 подобни елемента в този проект, под подобни имам предвид малки, които трябва да ги измислия по-добре .

**Comment by botodorov** [comment]
Оправено и оптимизирано с друг елемент
